using UnityEngine;

namespace Goodgulf.Builder
{
    /// <summary>
    /// Handles collision enter and exit events for this GameObject.
    /// Useful for debugging physics interactions and visualizing contact points.
    /// </summary>
    public class ColliderEvents : MonoBehaviour
    {
        /// <summary>
        /// Called automatically by Unity when this collider
        /// starts colliding with another collider.
        /// </summary>
        /// <param name="collision">
        /// Information about the collision, including the other object
        /// and all contact points.
        /// </param>
        void OnCollisionEnter(Collision collision)
        {
            // Log the names of the two GameObjects involved in the collision
            Debug.Log(
                "Collision of " + this.gameObject.name +
                " and " + collision.gameObject.name
            );

            // Loop through all contact points generated by the collision
            foreach (ContactPoint contact in collision.contacts)
            {
                // Draw a ray at each contact point in the direction of the surface normal
                // This helps visualize how and where the objects are colliding
                Debug.DrawRay(contact.point, contact.normal, Color.white);
            }
        }

        /// <summary>
        /// Called automatically by Unity when this collider
        /// stops colliding with another collider.
        /// </summary>
        /// <param name="collision">
        /// Information about the collision that just ended.
        /// </param>
        void OnCollisionExit(Collision collision)
        {
            // Log that the collision between the two GameObjects has ended
            Debug.Log(
                "No longer collision of " + this.gameObject.name +
                " and " + collision.gameObject.name
            );
        }
    }
}
